In [3]:
pip install datasets

Requirement already satisfied: datasets in c:\users\sushant\anaconda3\lib\site-packages (4.0.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: filelock in c:\users\sushant\anaconda3\lib\site-packages (from datasets) (3.13.1)
Requirement already satisfied: numpy>=1.17 in c:\users\sushant\anaconda3\lib\site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in c:\users\sushant\anaconda3\lib\site-packages (from datasets) (21.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\users\sushant\anaconda3\lib\site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\sushant\anaconda3\lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\sushant\anaconda3\lib\site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in c:\users\sushant\anaconda3\lib\site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in c:\users\sushant\anaconda3\lib\site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in c:\users\sushant\anaconda3\lib\site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2024.3.1)
Requirement already satisfied: huggingface-hub>=0.24.0 in c:\users\sushant\anaconda3\lib\site-packages (from datasets) (0.34.4)
Requirement already satisfied: packaging in c:\users\sushant\anaconda3\lib\site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\sushant\anaconda3\lib\site-packages (from datasets) (6.0.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\sushant\anaconda3\lib\site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.9.5)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\sushant\anaconda3\lib\site-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sushant\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sushant\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sushant\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sushant\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (2025.10.5)
Requirement already satisfied: colorama in c:\users\sushant\anaconda3\lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sushant\anaconda3\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sushant\anaconda3\lib\site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sushant\anaconda3\lib\site-packages (from pandas->datasets) (2023.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\sushant\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\sushant\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\sushant\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\sushant\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\sushant\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.9.3)
Requirement already satisfied: six>=1.5 in c:\users\sushant\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ---------------------------------------- 0.0/116.3 kB ? eta -:--:--
   --- ------------------------------------ 10.2/116.3 kB ? eta -:--:--
   ---------- ---------------------------- 30.7/116.3 kB 640.0 kB/s eta 0:00:01
   ------------- ------------------------- 41.0/116.3 kB 393.8 kB/s eta 0:00:01
   ------------------------ -------------- 71.7/116.3 kB 435.7 kB/s eta 0:00:01
   --------------------------------- ---- 102.4/116.3 kB 490.2 kB/s eta 0:00:01
   -------------------------------------- 116.3/116.3 kB 484.1 kB/s eta 0:00:00
Installing collected packages: dill
Successfully installed dill-0.3.8

WARNING: Skipping C:\Users\SUSHANT\anaconda3\Lib\site-packages\scipy-1.13.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\SUSHANT\anaconda3\Lib\site-packages\scipy-1.13.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\SUSHANT\anaconda3\Lib\site-packages\scipy-1.13.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\SUSHANT\anaconda3\Lib\site-packages\scipy-1.13.1.dist-info due to invalid metadata entry 'name'

### Load Dataset

In [53]:
from datasets import load_dataset

dataset = load_dataset("Divyaamith/Kaggle-Resume")

Repo card metadata block was not found. Setting CardData to empty.

In [55]:
import pandas as pd

df = dataset['train'].to_pandas()

print(df.shape)
df.head()

(2484, 4)

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

### Text Cleaning

In [14]:
pip install nltk

Collecting nltkNote: you may need to restart the kernel to use updated packages.

WARNING: Skipping C:\Users\SUSHANT\anaconda3\Lib\site-packages\scipy-1.13.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\SUSHANT\anaconda3\Lib\site-packages\scipy-1.13.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\SUSHANT\anaconda3\Lib\site-packages\scipy-1.13.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping C:\Users\SUSHANT\anaconda3\Lib\site-packages\scipy-1.13.1.dist-info due to invalid metadata entry 'name'

  Downloading nltk-3.9.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in c:\users\sushant\anaconda3\lib\site-packages (from nltk) (8.3.0)
Requirement already satisfied: joblib in c:\users\sushant\anaconda3\lib\site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.1.15-cp312-cp312-win_amd64.whl.metadata (41 kB)
     ---------------------------------------- 0.0/41.5 kB ? eta -:--:--
     --------- ------------------------------ 10.2/41.5 kB ? eta -:--:--
     ------------------ ------------------- 20.5/41.5 kB 320.0 kB/s eta 0:00:01
     ------------------ ------------------- 20.5/41.5 kB 320.0 kB/s eta 0:00:01
     ------------------ ------------------- 20.5/41.5 kB 320.0 kB/s eta 0:00:01
     ------------------ ------------------- 20.5/41.5 kB 320.0 kB/s eta 0:00:01
     ------------------ ------------------- 20.5/41.5 kB 320.0 kB/s eta 0:00:01
     ------------------ ------------------- 20.5/41.5 kB 320.0 kB/s eta 0:00:01
     ------------------ ------------------- 20.5/41.5 kB 320.0 kB/s eta 0:00:01
     ------------------ ------------------- 20.5/41.5 kB 320.0 kB/s eta 0:00:01
     ------------------ ------------------- 20.5/41.5 kB 320.0 kB/s eta 0:00:01
     ------------------ ------------------- 20.5/41.5 kB 320.0 kB/s eta 0:00:01
     ------------------ ------------------- 20.5/41.5 kB 320.0 kB/s eta 0:00:01
     ------------------ ------------------- 20.5/41.5 kB 320.0 kB/s eta 0:00:01
     ------------------ ------------------- 20.5/41.5 kB 320.0 kB/s eta 0:00:01
     ------------------ ------------------- 20.5/41.5 kB 320.0 kB/s eta 0:00:01
     --------------------------------------- 41.5/41.5 kB 40.8 kB/s eta 0:00:00
Requirement already satisfied: tqdm in c:\users\sushant\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\sushant\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.2-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
    --------------------------------------- 0.0/1.5 MB 640.0 kB/s eta 0:00:03
   - -------------------------------------- 0.0/1.5 MB 487.6 kB/s eta 0:00:04
   - -------------------------------------- 0.0/1.5 MB 487.6 kB/s eta 0:00:04
   - -------------------------------------- 0.0/1.5 MB 487.6 kB/s eta 0:00:04
   - -------------------------------------- 0.1/1.5 MB 217.9 kB/s eta 0:00:07
   - -------------------------------------- 0.1/1.5 MB 217.9 kB/s eta 0:00:07
   - -------------------------------------- 0.1/1.5 MB 217.9 kB/s eta 0:00:07
   - -------------------------------------- 0.1/1.5 MB 217.9 kB/s eta 0:00:07
   - -------------------------------------- 0.1/1.5 MB 217.9 kB/s eta 0:00:07
   - -------------------------------------- 0.1/1.5 MB 217.9 kB/s eta 0:00:07
   - -------------------------------------- 0.1/1.5 MB 217.9 kB/s eta 0:00:07
   - -------------------------------------- 0.1/1.5 MB 217.9 kB/s eta 0:00:07
   - -------------------------------------- 0.1/1.5 MB 217.9 kB/s eta 0:00:07
   - -------------------------------------- 0.1/1.5 MB 217.9 kB/s eta 0:00:07
   - -------------------------------------- 0.1/1.5 MB 217.9 kB/s eta 0:00:07
   - -------------------------------------- 0.1/1.5 MB 217.9 kB/s eta 0:00:07
   - -------------------------------------- 0.1/1.5 MB 217.9 kB/s eta 0:00:07
   -- ------------------------------------- 0.1/1.5 MB 121.3 kB/s eta 0:00:12
   -- ------------------------------------- 0.1/1.5 MB 121.3 kB/s eta 0:00:12
   -- ------------------------------------- 0.1/1.5 MB 121.3 kB/s eta 0:00:12
   -- ------------------------------------- 0.1/1.5 MB 121.3 kB/s eta 0:00:12
   -- ------------------------------------- 0.1/1.5 MB 121.3 kB/s eta 0:00:12
   --- ------------------------------------ 0.1/1.5 MB 100.1 kB/s eta 0:00:14
   --- ------------------------------------ 0.1/1.5 MB 100.1 kB/s eta 0:00:14
   --- ------------------------------------ 0.1/1.5 MB 107.8 kB/s eta 0:00:13
   --- ------------------------------------ 0.1/1.5 MB 107.8 kB/s eta 0:00:13
   --- ------------------------------------ 0.1/1.5 MB 107.8 kB/s eta 0:00:13
   --- ------------------------------------ 0.1/1.5 MB 107.8 kB/s eta 0:00:13
   ---- ----------------------------------- 0.2/1.5 MB 117.8 kB/s eta 0:00:12
   ----- ---------------------------------- 0.2/1.5 MB 125.5 kB/s eta 0:00:11
   ----- ---------------------------------- 0.2/1.5 MB 125.5 kB/s eta 0:00:11
   ----- ---------------------------------- 0.2/1.5 MB 125.5 kB/s eta 0:00:11
   ----- ---------------------------------- 0.2/1.5 MB 125.5 kB/s eta 0:00:11
   ----- ---------------------------------- 0.2/1.5 MB 125.5 kB/s eta 0:00:11
   ----- ---------------------------------- 0.2/1.5 MB 114.2 kB/s eta 0:00:12
   ----- ---------------------------------- 0.2/1.5 MB 123.9 kB/s eta 0:00:11
   ----- ---------------------------------- 0.2/1.5 MB 123.9 kB/s eta 0:00:11
   ------ --------------------------------- 0.2/1.5 MB 124.3 kB/s eta 0:00:11
   ------ --------------------------------- 0.2/1.5 MB 124.3 kB/s eta 0:00:11
   ------ --------------------------------- 0.2/1.5 MB 124.3 kB/s eta 0:00:11
   ------ --------------------------------- 0.3/1.5 MB 124.8 kB/s eta 0:00:11
   ------ --------------------------------- 0.3/1.5 MB 124.8 kB/s eta 0:00:11
   ------ --------------------------------- 0.3/1.5 MB 124.8 kB/s eta 0:00:11
   ------ --------------------------------- 0.3/1.5 MB 124.8 kB/s eta 0:00:11
   ------ --------------------------------- 0.3/1.5 MB 124.8 kB/s eta 0:00:11
   ------ --------------------------------- 0.3/1.5 MB 124.8 kB/s eta 0:00:11
   ------ --------------------------------- 0.3/1.5 MB 124.8 kB/s eta 0:00:11
   ------- -------------------------------- 0.3/1.5 MB 115.9 kB/s eta 0:00:11
   ------- -------------------------------- 0.3/1.5 MB 117.2 kB/s eta 0:00:11
   ------- -------------------------------- 0.3/1.5 MB 117.2 kB/s eta 0:00:11
   ------- -------------------------------- 0.3/1.5 MB 117.2 kB/s eta 0:00:11
   ------- -------------------------------- 0.3/1.5 MB 117.2 kB/s eta 0:00:11
   ------- -------------------------------- 0.3/1.5 MB 117.2 kB/s eta 0:00:11
   ------- -------------------------------- 0.3/1.5 MB 117.2 kB/s eta 0:00:11
   -------- ------------------------------- 0.3/1.5 MB 113.1 kB/s eta 0:00:11
   -------- ------------------------------- 0.3/1.5 MB 113.1 kB/s eta 0:00:11
   -------- ------------------------------- 0.3/1.5 MB 113.1 kB/s eta 0:00:11
   -------- ------------------------------- 0.3/1.5 MB 113.1 kB/s eta 0:00:11
   -------- ------------------------------- 0.3/1.5 MB 113.1 kB/s eta 0:00:11
   -------- ------------------------------- 0.3/1.5 MB 113.1 kB/s eta 0:00:11
   -------- ------------------------------- 0.3/1.5 MB 105.7 kB/s eta 0:00:12
   -------- ------------------------------- 0.3/1.5 MB 105.7 kB/s eta 0:00:12
   -------- ------------------------------- 0.3/1.5 MB 105.7 kB/s eta 0:00:12
   -------- ------------------------------- 0.3/1.5 MB 105.7 kB/s eta 0:00:12
   -------- ------------------------------- 0.3/1.5 MB 105.7 kB/s eta 0:00:12
   -------- ------------------------------- 0.3/1.5 MB 105.7 kB/s eta 0:00:12
   -------- ------------------------------- 0.3/1.5 MB 105.7 kB/s eta 0:00:12
   -------- ------------------------------- 0.3/1.5 MB 101.8 kB/s eta 0:00:12
   -------- ------------------------------- 0.3/1.5 MB 101.8 kB/s eta 0:00:12
   --------- ------------------------------ 0.4/1.5 MB 104.1 kB/s eta 0:00:12
   --------- ------------------------------ 0.4/1.5 MB 104.1 kB/s eta 0:00:12
   --------- ------------------------------ 0.4/1.5 MB 104.1 kB/s eta 0:00:12
   --------- ------------------------------ 0.4/1.5 MB 104.1 kB/s eta 0:00:12
   --------- ------------------------------ 0.4/1.5 MB 101.5 kB/s eta 0:00:12
   --------- ------------------------------ 0.4/1.5 MB 101.5 kB/s eta 0:00:12
   --------- ------------------------------ 0.4/1.5 MB 101.5 kB/s eta 0:00:12
   --------- ------------------------------ 0.4/1.5 MB 101.5 kB/s eta 0:00:12
   --------- ------------------------------ 0.4/1.5 MB 101.5 kB/s eta 0:00:12
   ---------- ----------------------------- 0.4/1.5 MB 101.4 kB/s eta 0:00:12
   ---------- ----------------------------- 0.4/1.5 MB 101.4 kB/s eta 0:00:12
   ---------- ----------------------------- 0.4/1.5 MB 101.4 kB/s eta 0:00:12
   ---------- ----------------------------- 0.4/1.5 MB 101.4 kB/s eta 0:00:12
   ---------- ----------------------------- 0.4/1.5 MB 99.6 kB/s eta 0:00:12
   ---------- ----------------------------- 0.4/1.5 MB 99.6 kB/s eta 0:00:12
   ---------- ----------------------------- 0.4/1.5 MB 99.6 kB/s eta 0:00:12
   ---------- ----------------------------- 0.4/1.5 MB 99.6 kB/s eta 0:00:12
   ---------- ----------------------------- 0.4/1.5 MB 99.6 kB/s eta 0:00:12
   ---------- ----------------------------- 0.4/1.5 MB 99.6 kB/s eta 0:00:12
   ---------- ----------------------------- 0.4/1.5 MB 99.6 kB/s eta 0:00:12
   ---------- ----------------------------- 0.4/1.5 MB 99.6 kB/s eta 0:00:12
   ---------- ----------------------------- 0.4/1.5 MB 99.6 kB/s eta 0:00:12
   ---------- ----------------------------- 0.4/1.5 MB 99.6 kB/s eta 0:00:12
   ----------- ---------------------------- 0.4/1.5 MB 98.3 kB/s eta 0:00:11
   ----------- ---------------------------- 0.4/1.5 MB 98.3 kB/s eta 0:00:11
   ----------- ---------------------------- 0.5/1.5 MB 97.8 kB/s eta 0:00:11
   ----------- ---------------------------- 0.5/1.5 MB 97.8 kB/s eta 0:00:11
   ----------- ---------------------------- 0.5/1.5 MB 97.8 kB/s eta 0:00:11
   ----------- ---------------------------- 0.5/1.5 MB 97.8 kB/s eta 0:00:11
   ----------- ---------------------------- 0.5/1.5 MB 97.8 kB/s eta 0:00:11
   ------------ --------------------------- 0.5/1.5 MB 97.0 kB/s eta 0:00:11
   ------------ --------------------------- 0.5/1.5 MB 97.0 kB/s eta 0:00:11
   ------------ --------------------------- 0.5/1.5 MB 97.0 kB/s eta 0:00:11
   ------------ --------------------------- 0.5/1.5 MB 97.0 kB/s eta 0:00:11
   ------------ --------------------------- 0.5/1.5 MB 97.0 kB/s eta 0:00:11
   ------------ --------------------------- 0.5/1.5 MB 97.0 kB/s eta 0:00:11
   ------------ --------------------------- 0.5/1.5 MB 97.0 kB/s eta 0:00:11
   ------------ --------------------------- 0.5/1.5 MB 93.3 kB/s eta 0:00:12
   ------------ --------------------------- 0.5/1.5 MB 93.3 kB/s eta 0:00:12
   ------------ --------------------------- 0.5/1.5 MB 93.3 kB/s eta 0:00:12
   ------------ --------------------------- 0.5/1.5 MB 93.3 kB/s eta 0:00:12
   ------------ --------------------------- 0.5/1.5 MB 93.3 kB/s eta 0:00:12
   ------------ --------------------------- 0.5/1.5 MB 93.3 kB/s eta 0:00:12
   ------------ --------------------------- 0.5/1.5 MB 93.3 kB/s eta 0:00:12
   ------------- -------------------------- 0.5/1.5 MB 90.9 kB/s eta 0:00:12
   ------------- -------------------------- 0.5/1.5 MB 90.9 kB/s eta 0:00:12
   ------------- -------------------------- 0.5/1.5 MB 90.9 kB/s eta 0:00:12
   ------------- -------------------------- 0.5/1.5 MB 90.9 kB/s eta 0:00:12
   ------------- -------------------------- 0.5/1.5 MB 91.5 kB/s eta 0:00:11
   ------------- -------------------------- 0.5/1.5 MB 91.5 kB/s eta 0:00:11
   ------------- -------------------------- 0.5/1.5 MB 91.5 kB/s eta 0:00:11
   ------------- -------------------------- 0.5/1.5 MB 91.5 kB/s eta 0:00:11
   ------------- -------------------------- 0.5/1.5 MB 91.5 kB/s eta 0:00:11
   ------------- -------------------------- 0.5/1.5 MB 91.5 kB/s eta 0:00:11
   ------------- -------------------------- 0.5/1.5 MB 91.5 kB/s eta 0:00:11
   ------------- -------------------------- 0.5/1.5 MB 91.5 kB/s eta 0:00:11
   ------------- -------------------------- 0.5/1.5 MB 91.5 kB/s eta 0:00:11
   ------------- -------------------------- 0.5/1.5 MB 91.5 kB/s eta 0:00:11
   ------------- -------------------------- 0.5/1.5 MB 91.5 kB/s eta 0:00:11
   -------------- ------------------------- 0.5/1.5 MB 85.5 kB/s eta 0:00:12
   -------------- ------------------------- 0.5/1.5 MB 85.5 kB/s eta 0:00:12
   -------------- ------------------------- 0.5/1.5 MB 85.5 kB/s eta 0:00:12
   -------------- ------------------------- 0.5/1.5 MB 85.5 kB/s eta 0:00:12
   -------------- ------------------------- 0.6/1.5 MB 85.5 kB/s eta 0:00:12
   -------------- ------------------------- 0.6/1.5 MB 85.5 kB/s eta 0:00:12
   -------------- ------------------------- 0.6/1.5 MB 85.5 kB/s eta 0:00:12
   -------------- ------------------------- 0.6/1.5 MB 85.3 kB/s eta 0:00:12
   -------------- ------------------------- 0.6/1.5 MB 85.3 kB/s eta 0:00:12
   -------------- ------------------------- 0.6/1.5 MB 85.3 kB/s eta 0:00:12
   --------------- ------------------------ 0.6/1.5 MB 87.0 kB/s eta 0:00:11
   --------------- ------------------------ 0.6/1.5 MB 87.0 kB/s eta 0:00:11
   --------------- ------------------------ 0.6/1.5 MB 88.4 kB/s eta 0:00:11
   --------------- ------------------------ 0.6/1.5 MB 88.4 kB/s eta 0:00:11
   --------------- ------------------------ 0.6/1.5 MB 88.4 kB/s eta 0:00:11
   --------------- ------------------------ 0.6/1.5 MB 88.4 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.7 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.7 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.7 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.7 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.7 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.5 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.5 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.5 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.5 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.5 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.5 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.5 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.5 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.5 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.5 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.5 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.5 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.5 kB/s eta 0:00:11
   ---------------- ----------------------- 0.6/1.5 MB 87.5 kB/s eta 0:00:11
   ----------------- ---------------------- 0.6/1.5 MB 81.4 kB/s eta 0:00:11
   ----------------- ---------------------- 0.6/1.5 MB 81.4 kB/s eta 0:00:11
   ----------------- ---------------------- 0.7/1.5 MB 82.9 kB/s eta 0:00:11
   ----------------- ---------------------- 0.7/1.5 MB 82.9 kB/s eta 0:00:11
   ----------------- ---------------------- 0.7/1.5 MB 82.9 kB/s eta 0:00:11
   ----------------- ---------------------- 0.7/1.5 MB 82.9 kB/s eta 0:00:11
   ----------------- ---------------------- 0.7/1.5 MB 82.9 kB/s eta 0:00:11
   ------------------ --------------------- 0.7/1.5 MB 83.0 kB/s eta 0:00:10
   ------------------ --------------------- 0.7/1.5 MB 83.0 kB/s eta 0:00:10
   ------------------ --------------------- 0.7/1.5 MB 83.0 kB/s eta 0:00:10
   ------------------ --------------------- 0.7/1.5 MB 83.0 kB/s eta 0:00:10
   ------------------ --------------------- 0.7/1.5 MB 83.0 kB/s eta 0:00:10
   ------------------ --------------------- 0.7/1.5 MB 83.0 kB/s eta 0:00:10
   ------------------ --------------------- 0.7/1.5 MB 83.0 kB/s eta 0:00:10
   ------------------ --------------------- 0.7/1.5 MB 81.0 kB/s eta 0:00:11
   ------------------ --------------------- 0.7/1.5 MB 81.0 kB/s eta 0:00:11
   ------------------ --------------------- 0.7/1.5 MB 81.0 kB/s eta 0:00:11
   ------------------ --------------------- 0.7/1.5 MB 81.0 kB/s eta 0:00:11
   ------------------ --------------------- 0.7/1.5 MB 81.0 kB/s eta 0:00:11
   ------------------ --------------------- 0.7/1.5 MB 81.0 kB/s eta 0:00:11
   ------------------ --------------------- 0.7/1.5 MB 81.0 kB/s eta 0:00:11
   ------------------ --------------------- 0.7/1.5 MB 80.3 kB/s eta 0:00:10
   ------------------ --------------------- 0.7/1.5 MB 80.3 kB/s eta 0:00:10
   ------------------ --------------------- 0.7/1.5 MB 80.3 kB/s eta 0:00:10
   ------------------ --------------------- 0.7/1.5 MB 80.3 kB/s eta 0:00:10
   ------------------ --------------------- 0.7/1.5 MB 80.3 kB/s eta 0:00:10
   ------------------ --------------------- 0.7/1.5 MB 80.3 kB/s eta 0:00:10
   ------------------ --------------------- 0.7/1.5 MB 80.3 kB/s eta 0:00:10
   ------------------ --------------------- 0.7/1.5 MB 80.3 kB/s eta 0:00:10
   ------------------ --------------------- 0.7/1.5 MB 80.3 kB/s eta 0:00:10
   ------------------ --------------------- 0.7/1.5 MB 80.3 kB/s eta 0:00:10
   ------------------- -------------------- 0.7/1.5 MB 77.4 kB/s eta 0:00:11
   ------------------- -------------------- 0.7/1.5 MB 77.4 kB/s eta 0:00:11
   ------------------- -------------------- 0.7/1.5 MB 77.4 kB/s eta 0:00:11
   ------------------- -------------------- 0.7/1.5 MB 77.4 kB/s eta 0:00:11
   ------------------- -------------------- 0.7/1.5 MB 77.4 kB/s eta 0:00:11
   ------------------- -------------------- 0.7/1.5 MB 77.5 kB/s eta 0:00:10
   ------------------- -------------------- 0.7/1.5 MB 77.5 kB/s eta 0:00:10
   ------------------- -------------------- 0.7/1.5 MB 77.5 kB/s eta 0:00:10
   ------------------- -------------------- 0.7/1.5 MB 77.5 kB/s eta 0:00:10
   ------------------- -------------------- 0.7/1.5 MB 77.5 kB/s eta 0:00:10
   -------------------- ------------------- 0.8/1.5 MB 77.7 kB/s eta 0:00:10
   -------------------- ------------------- 0.8/1.5 MB 77.7 kB/s eta 0:00:10
   -------------------- ------------------- 0.8/1.5 MB 77.7 kB/s eta 0:00:10
   -------------------- ------------------- 0.8/1.5 MB 77.7 kB/s eta 0:00:10
   -------------------- ------------------- 0.8/1.5 MB 77.7 kB/s eta 0:00:10
   -------------------- ------------------- 0.8/1.5 MB 77.7 kB/s eta 0:00:10
   -------------------- ------------------- 0.8/1.5 MB 76.3 kB/s eta 0:00:10
   -------------------- ------------------- 0.8/1.5 MB 76.3 kB/s eta 0:00:10
   -------------------- ------------------- 0.8/1.5 MB 76.3 kB/s eta 0:00:10
   -------------------- ------------------- 0.8/1.5 MB 76.3 kB/s eta 0:00:10
   -------------------- ------------------- 0.8/1.5 MB 76.3 kB/s eta 0:00:10
   --------------------- ------------------ 0.8/1.5 MB 76.6 kB/s eta 0:00:10
   --------------------- ------------------ 0.8/1.5 MB 76.6 kB/s eta 0:00:10
   --------------------- ------------------ 0.8/1.5 MB 76.6 kB/s eta 0:00:10
   --------------------- ------------------ 0.8/1.5 MB 76.6 kB/s eta 0:00:10
   --------------------- ------------------ 0.8/1.5 MB 76.6 kB/s eta 0:00:10
   --------------------- ------------------ 0.8/1.5 MB 76.6 kB/s eta 0:00:10
   --------------------- ------------------ 0.8/1.5 MB 75.6 kB/s eta 0:00:10
   --------------------- ------------------ 0.8/1.5 MB 75.6 kB/s eta 0:00:10
   --------------------- ------------------ 0.8/1.5 MB 75.6 kB/s eta 0:00:10
   --------------------- ------------------ 0.8/1.5 MB 75.6 kB/s eta 0:00:10
   --------------------- ------------------ 0.8/1.5 MB 75.6 kB/s eta 0:00:10
   --------------------- ------------------ 0.8/1.5 MB 75.6 kB/s eta 0:00:10
   --------------------- ------------------ 0.8/1.5 MB 75.6 kB/s eta 0:00:10
   --------------------- ------------------ 0.8/1.5 MB 75.6 kB/s eta 0:00:10
   --------------------- ------------------ 0.8/1.5 MB 75.6 kB/s eta 0:00:10
   --------------------- ------------------ 0.8/1.5 MB 75.6 kB/s eta 0:00:10

In [57]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\SUSHANT\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\SUSHANT\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [59]:
def preprocess(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    words = text.split()
    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]
    return " ".join(words)

In [61]:
df['clean_resume'] = df['Resume_str'].apply(preprocess)

### TF-IDF

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer

job_description = """
Looking for Data Scientist with Python, Machine Learning,
SQL, NLP, Deep Learning and Statistics.
"""

clean_job = preprocess(job_description)

vectorizer = TfidfVectorizer(max_features=5000)
tfidf_matrix = vectorizer.fit_transform(df['clean_resume'])
job_vector = vectorizer.transform([clean_job])

### Cosine similarity

In [65]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(job_vector, tfidf_matrix)[0]
df['similarity_score'] = similarity

ranked = df.sort_values(by='similarity_score', ascending=False)
ranked[['Category','similarity_score']].head(10)

           Category  similarity_score
1762    ENGINEERING          0.237095
2153        BANKING          0.203284
2291           ARTS          0.183669
1142     CONSULTANT          0.178427
1218     CONSULTANT          0.177249
194        DESIGNER          0.166528
1348     AUTOMOBILE          0.157394
1339     AUTOMOBILE          0.144956
929     AGRICULTURE          0.142590
1303  DIGITAL-MEDIA          0.129487

### Skill Extraction

In [67]:
skill_list = ["python","java","sql","machine learning","deep learning","nlp","data analysis","excel","tableau","power bi","tensorflow","pytorch","c++"]

#skill matching

In [69]:
def extract_skills(text):
    found_skills = []
    for skill in skill_list:
        if skill in text:
            found_skills.append(skill)
    return found_skills

df['skills'] = df['clean_resume'].apply(extract_skills)

In [73]:
df['skill_count'] = df['skills'].apply(len)

In [75]:
df['skill_score'] = df['skill_count'] / df['skill_count'].max()

### Weighted scoring system

In [77]:
df['final_score'] = (0.8 * df['similarity_score']) + (0.2 * df['skill_score'])

ranked_final = df.sort_values(by='final_score', ascending=False)
ranked_final[['Category','final_score']].head(10)

                    Category  final_score
1762             ENGINEERING     0.389676
1348              AUTOMOBILE     0.325915
1218              CONSULTANT     0.308466
1303           DIGITAL-MEDIA     0.303590
926              AGRICULTURE     0.303216
1339              AUTOMOBILE     0.282631
1142              CONSULTANT     0.276075
2153                 BANKING     0.262627
331   INFORMATION-TECHNOLOGY     0.258226
662     BUSINESS-DEVELOPMENT     0.250533